- .release-please-manifest.json
- graphs/CHANGELOG.md
---
* feat(graphs,plots): expand support for multi-dimensional node attributes by @JPXKQX in https://github.com/ecmwf/anemoi-core/pull/48
* feat(graphs): New Edge Attribute: AttributeFromNode by @icedoom888 in https://github.com/ecmwf/anemoi-core/pull/62
* feat: support ReducedGaussianGridNodes by @JPXKQX in https://github.com/ecmwf/anemoi-core/pull/54
* pre-commits-for-models-graphs-dev by @sahahner in https://github.com/ecmwf/anemoi-core/pull/45
* ci(docs): bring ReadTheDocs CI pipeline by @JPXKQX in …
> chore(main): Preparing Next Release for  anemoi-graphs 0.4.3

- .release-please-manifest.json
- graphs/CHANGELOG.md
---
Version fix.
**Full Changelog**: https://github.com/ecmwf/anemoi-core/compare/anemoi-graphs-0.4.3...anemoi-graphs-0.4.4
---
> [!IMPORTANT]
> :warning: Merging this PR will:
> - Create a new release
> - Trigger deployment pipelines
> - Update package versions
**Before merging:**
- Ensure all tests pass
- Review the changelog carefully
- Get required approvals
[Release-please documentation](https://github.com/googleapis/release-please)
> chore(main): Preparing Next Release for  anemoi-graphs 0.4.4

- training/src/anemoi/training/config/graph/encoder_decoder_only.yaml
Updates the encoder-decoder graph configuration. It uses ReducedGaussianGridNodes instead of NPZFileNodes so that any user can access reduced Gaussian grids.
-   [ ] I have tested the changes on multiple GPUs / …
> fix(training,configs): update encoder-decoder graph

- .github/workflows/python-pull-request.yml
The "Test PR" action currently skips installing the python packages (for matrix.install-mode = "all") and the pytests fail due to missing packages.
Change the conditional statement of the installation step to always install packages if install-mode = "all"
CI fix
> ci: fix pr action

- models/pyproject.toml
> fix: revert models min torch version to 2.2

- graphs/pyproject.toml
- models/pyproject.toml
- training/docs/modules/schemas.rst
- training/pyproject.toml
Add subheadings to schema doc page
-   [x] Documentation update
----
📚 Documentation preview 📚: https://anemoi-training--149.org.readthedocs.build/en/149/
----
📚 Documentation preview 📚: https://anemoi-graphs--149.org.readthedocs.build/en/149/
----
📚 Documentation preview 📚: https://anemoi-models--149.org.readthedocs.build/en/149/
> docs: Add subheadings to schema doc page

- training/docs/user-guide/configuring.rst
- training/src/anemoi/training/commands/config.py
- training/src/anemoi/training/config/model/gnn.yaml
- training/src/anemoi/training/config/model/graphtransformer.yaml
- training/src/anemoi/training/config/model/transformer.yaml
- training/src/anemoi/training/schemas/base_schema.py
- training/src/anemoi/training/schemas/dataloader.py
- training/src/anemoi/training/schemas/hardware.py
The DatasetSchema in the DatalaoderSchema also allows dictionaries now to match the broad configuration options in anemoi-datasets. This PR also sets the paths and files in the HardwareSchema that are not referenced in the code to optional fields.
Closes #141 
-   [x] I have tested the changes on a single GPU
-   [x] If the new feature introduces modifications at the config level, I have made sure to update Pydantic Schemas and default configs accordingly
-   [x] I have ensured that the code is still pip-installable after the changes and …
> fix:  dataset schema too defined too strictly

- training/docs/user-guide/debugging.rst
- training/src/anemoi/training/config/diagnostics/plot/none.yaml
- training/src/anemoi/training/schemas/models/common_components.py
- training/src/anemoi/training/schemas/models/models.py
> fix: updates to schemas to correct minor pydantic issues

- training/src/anemoi/training/config/stretched.yaml
Small PR to update the stretched.yaml config file to be consistent with the relevant schema
Minor change to improve consistency between config templates and pydantic schemas
> fix: update stretched.yaml config to be consistent with schema

- graphs/pyproject.toml
> fix(graphs): torch_geometric version < 2.5

- graphs/src/anemoi/graphs/describe.py
- graphs/src/anemoi/graphs/inspect.py
This PR forces `anemoi-graphs` to load the graph directly to the CPU during the `inspect` and `describe` commands.
-   [x] I have tested the changes on a single GPU
-   [ ] I have run the …
> fix(graphs): load graphs to cpu during inspection

- training/src/anemoi/training/data/datamodule.py
- training/src/anemoi/training/data/dataset.py
- training/src/anemoi/training/utils/usable_indices.py
- training/tests/unit/utils/test_usable_indices.py
Renames `model_run_ids` to `trajectory_ids` to remove confusion with `run_ids`.
-   [ ] I have run the Benchmark Profiler against the old …
> fix: Rename model_run_ids as trajectory_ids

- training/docs/user-guide/overview.rst
Add reference in training "getting started guide" to support intersphinx linking from "main" docs pages.
-   [x] Documentation update
-   [ ] I have run the Benchmark …
> docs: Add reference in training getting started guide for intersphinx

- training/src/anemoi/training/config/graph/hierarchical_2level.yaml
- training/src/anemoi/training/config/graph/hierarchical_3level.yaml
- training/src/anemoi/training/schemas/graphs/base_graph.py
- training/src/anemoi/training/schemas/models/models.py
This PR fixes some config validation errors for the hierarchical graphs.
-   [ ] I have run the Benchmark Profiler against the old version …
> fix(configs,schemas): hierarchical schemas

- training/tests/integration/aicon/test_cicd_aicon_04_icon-dream_medium.yaml
> fix: integration tests

- training/src/anemoi/training/config/config.yaml
- training/tests/integration/aicon/test_cicd_aicon_04_icon-dream_medium.yaml
> fix: correct config comment regarding config_validation flag

- training/src/anemoi/training/commands/mlflow.py
When creating a new MLflow run ID only the run ID is saved. Additional metadata might be needed (tracking_uri, experiment_id, experiment_name). This PR dump additional metadata in a JSON file:
```
$ anemoi-training mlflow prepare --config-name=debug 
2025-04-15 13:52:45 INFO Access token refreshed: 0.1 seconds.
2025-04-15 13:52:46 INFO Creating new run_id: c4adb23be8e1455e872012db79dfb659
2025-04-15 13:52:46 INFO Saving run id in file in mlflow_metadata.json.
$ cat mlflow_metadata.json | python -m json.tool
{
"run_id": "c4adb23be8e1455e872012db79dfb659",
"experiment_id": "182",
"experiment_name": "anemoi-debug-ecm6116",
"tracking_uri": "https://mlflow.ecmwf.int/"
}
```
-   [x] New feature (non-breaking change which adds …
> feat: Improve MLflow metadata in mlflow prepare CLI dump

- training/pyproject.toml
- training/src/anemoi/training/config/hardware/files/example.yaml
- training/src/anemoi/training/config/hardware/paths/example.yaml
To be able to do a release of anemoi-training we need to bump the version of graphs and model since there had been breaking changes introduced.
Aside from this we also choosing to use null as defaults for the truncation matrices, as those are right now not needed to train any of the models and that facilitate the developer experience.
-   [ ] I ran the [complete Pytest …
> fix: update to null and bump versions

- .github/workflows/python-pull-request.yml
This is a follow-up to cc459e1506946ae111a58811d985208f9b75dbf3 #151
-   [ ] I have run the Benchmark Profiler against the old version of …
> ci: Clean remnants of tests/ directory

- training/pyproject.toml
- training/src/anemoi/training/config/graph/encoder_decoder_only.yaml
- training/src/anemoi/training/config/graph/hierarchical_2level.yaml
- training/src/anemoi/training/config/graph/hierarchical_3level.yaml
- training/src/anemoi/training/config/graph/limited_area.yaml
- training/src/anemoi/training/config/graph/multi_scale.yaml
- training/src/anemoi/training/config/graph/stretched_grid.yaml
Bump `anemoi-graphs` version required in anemoi-training to `0.5.2`. The `ZarrDatasetNodes` class has now been renamed to `AnemoiDatasetNodes`. `ZarrDatasetNodes` is still supported but will be deprecated in future releases.
-   [ ] I have tested the changes …
> fix(training): bump anemoi-graphs version to 0.5.2

- .github/workflows/python-pull-request.yml
Add parentheses in install-mode expression to obtain expected result, i.e. fromJSON('["all"]', when this is run as "schedule" or "workflow_dispatch". 
> ci: fix install mode in pr action

- training/src/anemoi/training/config/ensemble_crps.yaml
- training/src/anemoi/training/config/training/ensemble.yaml
- training/src/anemoi/training/schemas/training.py
- training/tests/integration/config/test_ensemble_crps.yaml
- training/tests/integration/conftest.py
- training/tests/integration/test_training_cycle.py
Adding integration tests for the CRPS ensemble.
-   [x] New feature (non-breaking change which adds functionality)
> test: add integration test for the crps ensemble

- models/src/anemoi/models/layers/ensemble.py
- models/src/anemoi/models/models/ens_encoder_processor_decoder.py
- models/src/anemoi/models/schemas/models.py
- training/src/anemoi/training/config/model/gnn_ens.yaml
- training/src/anemoi/training/config/model/graphtransformer_ens.yaml
- training/src/anemoi/training/config/model/transformer_ens.yaml
error - https://github.com/ecmwf/anemoi-core/actions/runs/15278237765
fix - https://github.com/ecmwf/anemoi-core/actions/runs/15299027451
> fix: remove activation entry from MLP noise block

- models/src/anemoi/models/models/encoder_processor_decoder.py
- models/src/anemoi/models/models/ens_encoder_processor_decoder.py
- models/src/anemoi/models/models/interpolator.py
- training/src/anemoi/training/train/forecaster/interpolator.py
This fixes a few breaking issues with the interpolator after the addition of new features:
- Added truncation_data and statsitics tendencies arguments.
- Added handling of truncation data to the interpolator in models.
- Removed second declaration of input_dim in encoder_processor_decoder. This is already declared in calculate_shapes_and_indices, and the second declaration overrides the custom one in the interpolator.
-   [ ] I have added tests that prove my fix is effective or that …
> fix(training, models): Update interpolator to work with new features

- training/src/anemoi/training/config/interpolator.yaml
- training/src/anemoi/training/diagnostics/plots.py
> fix: Plotting error when precip related params are not diagnostic 

- models/src/anemoi/models/schemas/processor.py
The model validator in the transformer schema checking the allowed extra config entries was not working as expected. 
The model validator now correctly checks the type of the allowed extra config entries
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contri …
> fix: pydantic model validator not working in transformer schema

- training/tests/integration/conftest.py
PR to update checkpoint from integration tests as current integration tests are failing in main
> fix: new checkpoint

- graphs/docs/conf.py
- graphs/src/anemoi/graphs/edges/builders/masking.py
- graphs/src/anemoi/graphs/edges/builders/multi_scale.py
- graphs/src/anemoi/graphs/export.py
- graphs/src/anemoi/graphs/generate/utils.py
- graphs/src/anemoi/graphs/nodes/attributes/area_weights.py
- graphs/src/anemoi/graphs/nodes/attributes/boolean_op.py
- graphs/tests/nodes/attributes/test_weights.py
- graphs/tests/nodes/test_icon.py
- training/src/anemoi/training/train/tasks/ensforecaster.py
- training/src/anemoi/training/train/tasks/forecaster.py
A few type hints and formatting fixes in graphs and training that the previous PR to drop 3.9 missed.
----
📚 Documentation preview 📚: …
> chore: Type hints and formatting for >=3.10

- training/pyproject.toml
> chore: update anemoi-utils dependency version

- training/tests/integration/conftest.py
- training/tests/integration/test_training_cycle.py
Improve conftest types and update with changes in ecmwf/anemoi-utils#186.
Depends on ecmwf/anemoi-utils#186 to be merged first.
> refactor: improve conftest types in training tests

- .github/workflows/integration-tests-hpc.yml
Update the integration test to run as the new user dedicated to testing. 
> ci: Update integration test hpc user

- training/src/anemoi/training/utils/mlflow_sync.py
Syncing offline runs was not checking any cleaning of hp_params, this PR addresses that problem.
> fix: mlflow sync cleaning

- .release-please-manifest.json
- models/CHANGELOG.md
- training/CHANGELOG.md
---
<details><summary>training: 0.6.3</summary>
* GraphInterpolator Lightning Module - add rollout member for compa… ([#496](https://github.com/ecmwf/anemoi-core/issues/496)) ([40aa71c](https://github.com/ecmwf/anemoi-core/commit/40aa71c8eb097442ce33e7f0ff82e81b0947716e))
</details>
<details><summary>models: 0.9.3</summary>
* Convert pre_processors from attribute to variable in models/encoder_processor_decoder ([#503](https://github.com/ecmwf/anemoi-core/issues/503)) ([60eb52b](https://github.com/ecmwf/anemoi-core/commit/60eb52b465 …
> chore: Release main

- graphs/src/anemoi/graphs/schemas/post_processors.py
Fixes the `RestrictEdgeLength` schema to be in line with the actual code
Fixes #470 
> fix(graph): update RestrictEdgeLength schema

- graphs/src/anemoi/graphs/processors/post_process.py
> fix(graphs): move edge_indinces to cpu for post processors

- training/src/anemoi/training/diagnostics/profilers.py
Remove this line that has no impact on the behaviour of the code.
```batch_idx + 1```
> fix: remove useless code

- models/src/anemoi/models/models/encoder_processor_decoder.py
- training/src/anemoi/training/config/diagnostics/evaluation.yaml
- training/src/anemoi/training/data/datamodule/singledatamodule.py
- training/src/anemoi/training/train/train.py
- training/src/anemoi/training/utils/worker_init.py
Various changes, see git history.
> Multi dataset update 1

- training/src/anemoi/training/diagnostics/callbacks/sanity.py
@fprill reported that following #334 transfer learning no longer works in interactive mode
This issue is now fixed by stopping the model from using a feature from the DDP strategy in ineractive mode
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor …
> fix: interactive mode
