ecmwf/anemoi-core

training/src/anemoi/training/diagnostics/plots.py
Fix for https://github.com/ecmwf/anemoi-core/issues/12
- PR migrated from https://github.com/ecmwf/anemoi-training/pull/208
- Results from mlflow - https://mlflow.ecmwf.int/#/experiments/5/runs/b71fd6acec7d4190b15e35f9100dbb8e/artifacts
=> fix(training, plots) Exclude nans from error colorbars

training/pyproject.toml
This PR bumps the required `anemoi-datasets` version of `anemoi-training`.
=> fix(training): bump anemoi-datasets required version to 0.5.13

models/CHANGELOG.md, models/src/anemoi/models/interface/__init__.py
Small change to allow predict_step to take an optional model_comm_group, like model.forward does.
This is needed for parallel-inference, which calls predict_step
=> feature(models): Add model comm group to predict_step 

models/src/anemoi/models/preprocessing/normalizer.py
This PR avoids storing large intermediate results during the normalization by computing it in-place, e.g.
``
x[..., :] = x[..., :] * self._norm_mul + self._norm_add # old version
x.mul_(self._norm_mul).add_(self._norm_add) # new version
``
Note that the in_place argument still works as expected, only the actual calculation is changed to be done in-place.
For 9km data the old version resulted in mini-peaks during the normalizer: 
| Version | Peak memory (GB, during normalization) |
|------|------|
| old | 32.62 |
| new | 17.73 |
This lines up with storing two additional intermediate results (multiplication, addition) @~8GB batch size in the old version.
=> fix: normalise in place to reduce memory

training/src/anemoi/training/config/graph/encoder_decoder_only.yaml, training/src/anemoi/training/config/graph/limited_area.yaml, training/src/anemoi/training/config/graph/multi_scale.yaml, training/src/anemoi/training/config/graph/stretched_grid.yaml
This PR updates the default graph configuration files. These changes suppress a deprecation warning generated by anemoi-graphs. `AreaWeights` class is dropped in favour of `SphericalAreaWeights` and `PlanarAreaWeights`.
=> fix: update graph configs to avoid DeprecationWarning for area weights

models/src/anemoi/models/models/hierarchical.py
This PR splits the hidden-most processor instantiation from the in-level processors. 
- The `level_process_num_layers` ([link](https://github.com/ecmwf/anemoi-core/blob/develop/training/src/anemoi/training/config/hierarchical.yaml#L23C3-L23C30)) specifies the number of layers for the intermediate level processors.
- The `num_layers` argument sets the value for the hidden-most level processor.
This PR extends the current functionality. The previous behaviour can be obtained by setting `num_layers` and `level_process_num_layers` to the same value.
=> feat(models): use num_layers of the processor in hierarchical graphs

.github/workflows/readthedocs-pr-update.yml, graphs/docs/requirements.txt
Sadly the initial read the docs action failed
This reverts the simplificiation which should fix it.
=> ci(docs): readthedocs ci

training/src/anemoi/training/diagnostics/plots.py
When the min or max value in the error maps is equal to zero, the plot function crashes because `vmax` or `vmin` is equal to `vcenter`.  This fix below seems to solve the problem.
I got this issue in the first epoch when trying to map the precipitation field.
=> Fix crash in diagnostic plots (colorbar limits)

training/CHANGELOG.md, training/src/anemoi/training/diagnostics/profilers.py, training/src/anemoi/training/train/profiler.py, training/src/anemoi/training/train/train.py
Previously the profilers model summary didn't work if your model was sharded across multiple GPUs. By moving '@rank_zero_only' around, it works now.
One use of this is we can use the Model Summary to count the FLOPs done per model, which is useful for benchmarking. Below I use it to compare the arithmetic intensity of the transformer model at n320 vs o1280 input resolution.
I have also snuck in a small change to `diagnostics.print_memory_summary`. Previously it was a 'DEBUG' level log, so you likely wouldn't see it even when `diagnostics.print_memory_summary = true`. Now it is "INFO"
=> fix(training): profiler 'Model Summary' works when sharding models over multiple GPUs

models/src/anemoi/models/models/encoder_processor_decoder.py
When `kernel_layers` is not set in the model config, it should return the pytoch default kernel. 
Changes: 
```
- OmegaConf.select(model_config, "model.layer_kernels") -> returns None if layer_kernels is not set
+ model_config.model.get("layer_kernels", {}) -> returns {} if layer_kernels is not set 
```
=> fix: default behaviour for kernel_layers when not set in config.

.github/workflows/readthedocs-pr-update.yml, graphs/.readthedocs.yaml, models/.readthedocs.yaml, training/.readthedocs.yaml
This limits the builds on RTD to avoid always building all documentations for PRs.
=> docs: cancel RTD builds on PRs without change

training/src/anemoi/training/data/dataset.py
This PR brings back the cpu memory savings from sharded dataloading [(#76)](https://github.com/ecmwf/anemoi-training/pull/76). At 9km, the max cpu memory usage goes down from ~70% to ~30%.
The sharded reading clashed with the recent changes to [Support masking of unconnected nodes (LAM)](https://github.com/ecmwf/anemoi-training/pull/171). Since anemoi-datasets currently doesn't support slicing and indexing in one operation like
``
x = self.data[start : end : self.timeincrement, :, :, grid_shard_indices]
``
the new version checks for the type of `grid_shard_indices` and does it in 2 steps if necessary. 
@Rilwan-Adewoyin @JPXKQX @b8raoult @floriankrb
=> fix: cpu memory savings of sharded dataloader

models/src/anemoi/models/layers/bounding.py, models/tests/layers/test_bounding.py
A bug affects `anemoi.models.layers.bounding.NormalizedReluBounding` if the order of the variable douring the call in config does not match the order of the variables in the torch array. This a problem emerged only when multiple variables were bounded at the same time with this procedure.
This is fixed by making sure that `self.norm_min_val` follows the same order as `self.data_index`.
=> fix:  bug in variables ordering in NormalizedReluBounding

.github/workflows/python-publish.yml, .github/workflows/release-please.yml, .release-please-config.json, .release-please-manifest.json
This is a first proposal for a release please implementation and Python publish workflow that works with mono-repos
=> ci: Propose release-please implementation

.release-please-manifest.json, training/CHANGELOG.md
---
* make flash attention configurable ([#60](https://github.com/ecmwf/anemoi-core/issues/60)) ([41fcab6](https://github.com/ecmwf/anemoi-core/commit/41fcab6335b334fdbebeb944c904cdbea6388889))
* Model Freezing ❄️  ([#61](https://github.com/ecmwf/anemoi-core/issues/61)) ([54e42cf](https://github.com/ecmwf/anemoi-core/commit/54e42cf42a47e00be96b464f501f6a462cd1bca4))
* **models:** normalization layers ([#47](https://github.com/ecmwf/anemoi-core/issues/47)) ([0e1c7c4](https://github.com/ecmwf/anemoi-core/commit/0e1c7c4840138debf877bb …
=> chore(main): Preparing Next Release for  training 0.3.3

graphs/src/anemoi/graphs/describe.py, graphs/src/anemoi/graphs/inspect.py
torch 2.6 changed the default behavior for torch.load from `weights_only=False` to `weights_only=True`. As a result `anemoi-graphs describe` and `anemoi-graphs inspect` doesnt work in torch v2.6 and beyond.
the following small change fixes this.
```python
-  torch.load()
+ torch.load(weights_only=False)
```
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] I have performed a self-review of my code
=> fix(graphs): load weights works for torch v2.6 and beyond

training/src/anemoi/training/diagnostics/callbacks/__init__.py, training/src/anemoi/training/diagnostics/callbacks/stopping.py, training/tests/diagnostics/callbacks/test_timelimit.py
Add TimeLimit Callback
- Stops training if time limit is reached
- Log to file the last checkpoint
Closes #114 
```python
from anemoi.training.diagnostics.callbacks.stopping import TimeLimit
TimeLimit(limit = '24h', record_file = 'PATH/TO/LOG.txt')
```
=> feat(training): Add initial TimeLimit callback

.release-please-manifest.json, models/CHANGELOG.md
---
* make flash attention configurable ([#60](https://github.com/ecmwf/anemoi-core/issues/60)) ([41fcab6](https://github.com/ecmwf/anemoi-core/commit/41fcab6335b334fdbebeb944c904cdbea6388889))
* **models:** Copy Imputer ([#72](https://github.com/ecmwf/anemoi-core/issues/72)) ([4690ed5](https://github.com/ecmwf/anemoi-core/commit/4690ed52b9996bc149417d3724c5cd68c234573f))
* **models:** normalization layers ([#47](https://github.com/ecmwf/anemoi-core/issues/47)) ([0e1c7c4](https://github.com/ecmwf/anemoi-core/commit/0e1c7c4840138deb …
=> chore(main): Preparing Next Release for  models 0.4.2

.github/workflows/push-to-private.yml
Ci fix: update the push_to_private github action to activate on pushes to main (instead of develop)
Due to the switch from develop to main, this github action needs to be updated.
=> ci: update develop to main in push_to_private action

graphs/tests/nodes/test_zarr.py
The exception raised by this test depends on the zarr version. In zarr 2, it raises `zarr.errors.PathNotFoundError` but in zarr3 it raises `zarr.errors.FileNotFoundError`.
-   [ ] I have tested the changes on …
=> fix(graphs): make exception agnostic of zarr version

graphs/docs/graphs/node_attributes/boolean_operations.rst, graphs/docs/graphs/node_attributes/zarr_attribute.rst, graphs/docs/graphs/node_coordinates/zarr_dataset.rst, graphs/docs/index.rst, graphs/docs/overview.rst, graphs/src/anemoi/graphs/nodes/attributes.py, graphs/src/anemoi/graphs/nodes/builders/from_file.py, models/docs/modules/data_indices.rst, training/src/anemoi/training/data/dataset.py, training/src/anemoi/training/schemas/graphs/node_attributes_schemas.py, training/src/anemoi/training/schemas/graphs/node_schemas.py
Refering to Zarr outside of the anemoi-datasets package breaks the encapsulation principle.
-   [x] Documentation update
-   [ ] I have run the Benchmark Profiler …
=> docs: fix documentation to refer to anemoi datasets instead of zarr datasets

training/src/anemoi/training/config/graph/stretched_grid.yaml, training/src/anemoi/training/config/stretched.yaml, training/src/anemoi/training/schemas/training.py
This is a fix to an error raised by pydantic when using `ReweightedGraphNodeAttribute` with the `no_validation: False`.
The node attribute "cutout" is renamed to "cutout_mask" (same as for config/graph/limited_area.yaml)
-   [ ] I have tested the changes on a …
=> fix(training,schema): error when using ReweightedGraphNodeAttribute

training/pyproject.toml
The top level ruff lint options in the training pyproject are deprecated:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `training/pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
This updates the settings according to the above warning.
=> chore(training): Update ruff lint settings

training/pyproject.toml, training/src/anemoi/training/diagnostics/mlflow/auth.py, training/src/anemoi/training/diagnostics/mlflow/utils.py
There are two parts in training that talk to the mlflow endpoint direct: the authentication layer, and the health check that verifies if the authentication succeeded and we can reach the server.
These send requests to the mlflow endpoint directly, and if it fails the code will crash.
This PR adds a retry mechanic, where it will retry those requests if the failure is caused by a recoverable HTTP response (bad gateway, service unavailable, etc). This will make training less prone to crashes from intermittent network issues.
-   [x] New feature (non-breaking change which adds functionality)
-   [x] I …
=> feat(mlflow): Make direct endpoint calls robust

.github/workflows/integration-tests.yml
The integration test workflow fails due to a missing reference in the 'uses' attribute pointing to the action in reusable workflows. This PR adds a reference to fix the syntax.
=> fix: add reference in integration test workflow

.github/workflows/integration-tests.yml, training/docs/dev/testing.rst, training/pytest.ini, training/tests/conftest.py, training/tests/integration/conftest.py, training/tests/integration/test_training_cycle.py
Previously, the --longtests option for the pytest suite was only available in the integration test folder. Now, it is available on the top-level test as well.
The marker has changed to @pytest.mark.longtests.
----
📚 Documentation preview 📚: https://anemoi-training--200.org.readthedocs.build/en/200/
----
📚 Documentation preview 📚: …
=> fix: fix --longtests not available

training/tests/integration/conftest.py
Adds a fixture to the integration test set-up that navigates to the repo's root dir at the beginning of each test.
This is needed because we use config files in anemoi-core/training//src/anemoi/training/config/ with relative paths for hydra, as well as config files from the integration test dir in anemoi-core.
This fixes the fast integration tests failing on the downstream-ci where tests are not run from the root dir of anemoi-core.
Error message from downstream-ci on anemoi-utils:
=========================== short test summary info ============================
ERROR tests/integration/test_training_cycle.py::test_config_validation_architecture_configs[architecture_config0] - FileNotFoundError: [Errno 2] No such file or directory: …
=> test: fix relative paths for downstream ci

training/src/anemoi/training/train/train.py
Fix bug introduced in https://github.com/ecmwf/anemoi-core/pull/164 when running a training with multiple GPUs/tasks. This a quick fix and a more long term and robust solution might be investigated: https://github.com/ecmwf/anemoi-core/issues/240. 
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I …
=> fix: Checkpoint path check for multiple tasks/GPUs training

models/src/anemoi/models/interface/__init__.py, training/src/anemoi/training/config/model/gnn.yaml, training/src/anemoi/training/config/model/gnn_ens.yaml, training/src/anemoi/training/config/model/graphtransformer.yaml, training/src/anemoi/training/config/model/graphtransformer_ens.yaml, training/src/anemoi/training/config/model/transformer.yaml, training/src/anemoi/training/config/model/transformer_ens.yaml, training/src/anemoi/training/train/forecaster/forecaster.py
When running anemoi-inference the `predict_step` function of the model interface is called, which in turn calls the forward function of the model. The forward function of `AnemoiEnsModelEncProcDec` however takes more arguments which needs to be passed from `anemoi-inference`. 
Introduction of a new `AnemoiEnsModelInterface`, which passes the arguments correctly.
For that, I've introduced a `model.interface` keyword in the model configs. This is a breaking change since the keyword is required. 
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] I have trained a deterministic and kcrps model and preformed inference
-   [ ] I have updated the …
=> fix: Fix inference with kcrps 

training/src/anemoi/training/config/debug_ens.yaml, training/src/anemoi/training/config/training/ensemble.yaml
The default configs for the ensemble training were not working with the new loss refactor. This PR creates a `config/training/ensemble.yaml` that sets default values for training with ensemble members.
A new `ensemble.yaml` file was required because the `default.yaml` would set `mse` as a `training.validation_metrics`, which can be extended by other metrics but cannot be fully overwritten (mse would always be part of the validation_metrics). The MSE metric, however, is not compatible with the `GraphEnsForecaster` model. 
-   [x] I have tested the changes on a single GPU
-   [x] I have tested the changes on multiple GPUs / multi-node setups
-   [x] I have tested inference on a …
=> fix: Adapt ensemble configs to work with loss refactor. 

training/src/anemoi/training/diagnostics/mlflow/utils.py
Reduce the number of parameters logged to increase MLflow spread.
Recently, the metadata of the variables has been increased in size and information. Not all this information needs to be logged to mllfow, where it reduces the speed.
-   [ ] I have tested the …
=> fix(training): no logging variable metadata to mlflow

training/src/anemoi/training/losses/base.py, training/src/anemoi/training/losses/scaler_tensor.py
The Loss Scaler was being moved from the cpu to the gpu every loss calculation.
When running with o96 on 1 GPU on ATOS the it/s changes from 3.10 -> 3.65.
-   [x] I have tested the changes on a single GPU
-   [x] I have tested the changes on multiple GPUs / multi-node setups
-   [x] I have run the Benchmark …
=> fix: Move scaler to device in scale

.github/workflows/integration-tests-hpc.yml
This PR changes the ci workflow for integration tests on the hpc.
- It adds a notify-team step, as for the integration test workflow on github runners, to notify the AnemoiSecurity group if tests fail -- currently only the person who set up the cron job gets a notification.
- It makes the pytest output more verbose.
=> ci: add notify team step to hpc workflow

graphs/src/anemoi/graphs/generate/transforms.py, graphs/src/anemoi/graphs/nodes/attributes/area_weights.py, graphs/src/anemoi/graphs/nodes/builders/base.py
Fixes #362 
SphericalAreaWeights needs float64 precision input to work as intended for high resolution graphs
#362 
=> fix: SphericalAreaWeights

graphs/src/anemoi/graphs/create.py
The warning currently thrown by `anemoi-graphs create` when a graph already exists is too subtle. If you don’t scroll up in a successful-looking output, you will miss that the graph creation failed. Here’s an **example output from a failed graph creation** from  my terminal: 
I began working on a new PR because I thought there was a bug elsewhere,  because I didn’t notice the warning.
To make failure more noisy, I’ve changed the behavior to raise an explicit error instead of a warning:
##
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also responsible for verifying these aspects and …
=> fix(graphs): throw error instead of raising warning when graph exists. 

training/tests/integration/config/test_config.yaml, training/tests/integration/config/test_ensemble_crps.yaml, training/tests/integration/config/test_lam.yaml, training/tests/integration/config/test_stretched.yaml
Update paths to test data in order to clean up the folder anemoi-integration-tests in the object store. When this is merged, I'll delete the old copies of the datasets.
Just maintenance
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agre …
=> chore: update paths after organizing training test data in ewc

training/src/anemoi/training/losses/loss.py, training/src/anemoi/training/losses/scalers/variable.py, training/src/anemoi/training/losses/scalers/variable_level.py, training/src/anemoi/training/train/forecaster/forecaster.py, training/src/anemoi/training/utils/variables_metadata.py, training/tests/unit/train/test_loss_scaling.py, training/tests/unit/utils/test_variable_grouping.py
Closes #404 
Some datasets have malformed metadata, and fail on the level retrieval
This updates the logic, including checks for surface level if attempting to use the variable metadata.
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agr …
=> fix: Update level retrieval logic

graphs/src/anemoi/graphs/create.py
Revert PR #379 .
Thanks to @havardhhaugen for spotting this.
Raising an error during graph creation will break multi-GPU training. Currently, one limitation of `anemoi-graphs` is that it does not support distributed creation. For example, during multi-GPU training with on-the-fly graph creation, the same graph is created on all GPUs. In this case, raising an error will cause the code to fail on some of the GPUs.
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also responsible for verifying these aspects and requesting changes if they are not adequately addressed. For guidelines about those …
=> fix(graphs): revert PR #397

.release-please-manifest.json, graphs/CHANGELOG.md, models/CHANGELOG.md, training/CHANGELOG.md
---
<details><summary>training: 0.6.1</summary>
* Add extensible checkpoint loading system                                                                                     │ ([ebc55fc](https://github.com/ecmwf/anemoi-core/commit/ebc55fc9564d03d8e090bafab2fdd93042daa6cf))
* Extend DelayedScalers into arbitary UpdatingScalers [#371](https://github.com/ecmwf/anemoi-core/issues/371)  ([b9d7726](https://github.com/ecmwf/anemoi-core/commit/b9d772659679b1d1744c9be6a6602673eb9e6969))
* **models:** Nan locations in imputer calculated on …
=> chore: Release main

training/src/anemoi/training/diagnostics/callbacks/plot.py, training/src/anemoi/training/losses/scaler_tensor.py
Sharding over grid dimension for nan_mask_weights scaler fails at the moment on main.
Changes:
- do not validate sharded dims for scalers
- deep copy of loss function to gather nan scaler over grid dim for plotloss callback
Tested for:
- sharding over grid dimension
- with and without nan_mask_weights
- with and without imputer
The scaler validation, which is triggered after every scaler definition and update, was causing an error, as the nan scaler is shared over the grid dimension.
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also responsible for verifying these aspects and requesting …
=> fix(training): sharding nan_loss_mask scaler

models/src/anemoi/models/models/encoder_processor_decoder.py
Closes #502 
Fixes a bug, where encoder processor decoder model called `self.pre_processors` rather than `pre_processors` in `predict_step`
#502 
=> fix: convert pre_processors from attribute to variable in models/encoder_processor_decoder

.github/workflows/pr-release.yml
The upcoming checkpoint migrations rely on the migration files having a reference to the next anemoi-models version that the migration is targeting. This is done with a placeholder `%NEXT_ANEMOI_MODELS_VERSION%` that is replaced on release time with the version being released.
This workflow does that. It runs on the release-please (DeployDuck) PRs, and it updates the placeholder in all the migration files and commits it to the release-please branch. If there are no migrations to update, it does nothing. Since release-please regularly force-pushes its branch to the latest state of main, any new migrations made since the opening of the PR will be automatically updated.
When the release PR is merged, the migrations go into main with the correct versions.
I made it a general workflow where we …
=> ci: Add checkpoint migrations workflow

.github/workflows/integration-tests-hpc.yml
If the benchmark CI test queues for over an hour, the github action will timeout, failing the test.
This job increases the timeout to 6 hrs, so that it should run somepoint during the night.
This doesnt impact the slurm timeout, which is still 1 hour. this change just effects how long github actions will wait for the slurm job to complete.
By opening this …
=> fix: increase timeout on benchmark github action

models/src/anemoi/models/migrations/migrator.py
The migrator was setting the wrong path for the migrations scripts. This yielded some warnings that migrations could not be loaded.
This fixes this, and changes the warning into an error, so that it can be detected with the integration tests in the future.
By opening this pull request, I affirm that all authors agree to the [Contributor License …
=> fix: set correct base package for migrations imports

training/docs/modules/losses.rst, training/docs/user-guide/training.rst
https://github.com/ecmwf/anemoi-core/issues/506
Outdated docs about loss function.
----
📚 Documentation preview 📚: https://anemoi-training--525.org.readthedocs.build/en/525/ …
=> fix: outdated docs for loss functions

models/src/anemoi/models/models/encoder_processor_decoder.py
Fix a bug were grid_shard_shapes were applied to the wrong dimension leading to errors when using uneven grid shards.
=> fix: truncation shard shapes

training/src/anemoi/training/diagnostics/callbacks/stopping.py
The PR fixed the TimeLimit callback to make it work when using multiple nodes.
Runs check time and log in file for the rank zero only.
ML workflows based on anemoi-training.
Slurm setup:
```
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --gpus-per-node=2
```
Before fix:
```
[2025-09-23 14:42:56,052][anemoi.training.diagnostics.callbacks.stopping][INFO] - Time limit of 2m reached. Stopping training.
[2025-09-23 14:42:56,052][anemoi.training.diagnostics.callbacks.stopping][INFO] - Time limit of 2m reached. Stopping training.
[2025-09-23 14:42:56,052][anemoi.training.diagnostics.callbacks.stopping][INFO] - Time limit of 2m reached. Stopping training.
[2025-09-23 14:42:56,052][anemoi.training.diagnostics.callbacks.stopping][INFO] - Time limit of 2m reached. Stopping training.
File …
```
=> fix: Make TimeLimit callback compliant with multiple nodes 

training/docs/user-guide/training.rst
Removed `_convert_: all`, see issue #561
----
📚 Documentation preview 📚: https://anemoi-training--576.org.readthedocs.build/en/576/
----
📚 Documentation preview 📚: …
=> fix(training): Correct Imputer Doc
